// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260206172825_AddSupportNotes")]
    partial class AddSupportNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Backend.Models.ClientTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("client_id");

                    b.Property<int>("Completed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("client_tasks");
                });

            modelBuilder.Entity("Backend.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("CheckEstado")
                        .HasColumnType("INTEGER")
                        .HasColumnName("check_estado")
                        .HasAnnotation("Relational:JsonPropertyName", "check_estado");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("empresa")
                        .HasAnnotation("Relational:JsonPropertyName", "empresa");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT")
                        .HasColumnName("estado")
                        .HasAnnotation("Relational:JsonPropertyName", "estado");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT")
                        .HasColumnName("observaciones")
                        .HasAnnotation("Relational:JsonPropertyName", "observaciones");

                    b.HasKey("Id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("Backend.Models.Pendiente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Actividad")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("actividad");

                    b.Property<string>("AudioFilePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("audio_file_path");

                    b.Property<string>("AudioTranscription")
                        .HasColumnType("TEXT")
                        .HasColumnName("audio_transcription");

                    b.Property<string>("CCEmails")
                        .HasColumnType("TEXT")
                        .HasColumnName("cc_emails");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<int>("DiasAntesNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(3)
                        .HasColumnName("dias_antes_notificacion");

                    b.Property<string>("EmailNotificacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("email_notificacion");

                    b.Property<string>("Empresa")
                        .HasColumnType("TEXT")
                        .HasColumnName("empresa");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<string>("FechaLimite")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_limite");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.ToTable("pendientes");
                });

            modelBuilder.Entity("Backend.Models.SupportNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("support_notes");
                });
#pragma warning restore 612, 618
        }
    }
}
